export default mockData = [
    {
      "id": "r_BrIgzYcwo1NAuG9dLbpg",
      "alias": "pai-northern-thai-kitchen-toronto-5",
      "name": "Pai Northern Thai Kitchen",
      "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/uAnTcmLEQJWkCUOtvZMALA/o.jpg",
      "is_closed": false,
      "url": "https://www.yelp.com/biz/pai-northern-thai-kitchen-toronto-5?adjust_creative=28gGfkLs3igtjVy61lh77Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=28gGfkLs3igtjVy61lh77Q",
      "review_count": 3647,
      "categories": [{ "alias": "thai", "title": "Thai" }],
      "rating": 4.4,
      "coordinates": { "latitude": 43.64784, "longitude": -79.38872 },
      "transactions": [],
      "price": "$$",
      "location": {
        "address1": "18 Duncan Street",
        "address2": "",
        "address3": "",
        "city": "Toronto",
        "zip_code": "M5H 3G8",
        "country": "CA",
        "state": "ON",
        "display_address": ["18 Duncan Street", "Toronto, ON M5H 3G8"]
      },
      "phone": "+14169014724",
      "display_phone": "+1 416-901-4724",
      "distance": 3009.3347434869856,
      "business_hours": [{ "day": "Monday", "start": "1100", "end": "2200" }],
      "attributes": {
        "business_temp_closed": null,
        "menu_url": null,
        "open24_hours": null,
        "waitlist_reservation": null
      }
    },
    {
      "id": "mZRKH9ngRY92bI_irrHq6w",
      "alias": "richmond-station-toronto",
      "name": "Richmond Station",
      "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/agCQCtFg1pwV4WRBBw8CAg/o.jpg",
      "is_closed": false,
      "url": "https://www.yelp.com/biz/richmond-station-toronto?adjust_creative=28gGfkLs3igtjVy61lh77Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=28gGfkLs3igtjVy61lh77Q",
      "review_count": 935,
      "categories": [{ "alias": "canadian", "title": "Canadian (New)" }],
      "rating": 4.4,
      "coordinates": { "latitude": 43.6513729, "longitude": -79.379285 },
      "transactions": [],
      "price": "$$$",
      "location": {
        "address1": "1 Richmond Street W",
        "address2": "",
        "address3": "",
        "city": "Toronto",
        "zip_code": "M5H 3W4",
        "country": "CA",
        "state": "ON",
        "display_address": ["1 Richmond Street W", "Toronto, ON M5H 3W4"]
      },
      "phone": "+16477481444",
      "display_phone": "+1 647-748-1444",
      "distance": 2911.814072486624,
      "business_hours": [{ "day": "Tuesday", "start": "1100", "end": "2200" }],
      "attributes": {
        "business_temp_closed": null,
        "menu_url": "https://richmondstation.ca/menu/",
        "open24_hours": null,
        "waitlist_reservation": null
      }
    },
    {
      "id": "_T7f2wUgNlJqxsR-cR89SQ",
      "alias": "scaramouche-restaurant-pasta-bar-and-grill-toronto",
      "name": "Scaramouche Restaurant Pasta Bar & Grill",
      "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/XeRT7r5JbhUSr2a6zSIqYg/o.jpg",
      "is_closed": false,
      "url": "https://www.yelp.com/biz/scaramouche-restaurant-pasta-bar-and-grill-toronto?adjust_creative=28gGfkLs3igtjVy61lh77Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=28gGfkLs3igtjVy61lh77Q",
      "review_count": 347,
      "categories": [{ "alias": "italian", "title": "Italian" }, { "alias": "french", "title": "French" }],
      "rating": 4.5,
      "coordinates": { "latitude": 43.68150266319956, "longitude": -79.39987971712722 },
      "transactions": [],
      "price": "$$$$",
      "location": {
        "address1": "1 Benvenuto Place",
        "address2": "",
        "address3": "",
        "city": "Toronto",
        "zip_code": "M4V 2L1",
        "country": "CA",
        "state": "ON",
        "display_address": ["1 Benvenuto Place", "Toronto, ON M4V 2L1"]
      },
      "phone": "+14169618011",
      "display_phone": "+1 416-961-8011",
      "distance": 839.7606384136095,
      "business_hours": [{ "day": "Wednesday", "start": "1100", "end": "2200" }],
      "attributes": {
        "business_temp_closed": null,
        "menu_url": null,
        "open24_hours": null,
        "waitlist_reservation": null
      }
    },
    {
      "id": "5XVE1NtoMNbXJJcLTj1qeA",
      "alias": "osteria-giulia-toronto",
      "name": "Osteria Giulia",
      "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/JJIEMnULhMXhgP1ClV8n9A/o.jpg",
      "is_closed": false,
      "url": "https://www.yelp.com/biz/osteria-giulia-toronto?adjust_creative=28gGfkLs3igtjVy61lh77Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=28gGfkLs3igtjVy61lh77Q",
      "review_count": 57,
      "categories": [{ "alias": "italian", "title": "Italian" }],
      "rating": 4.2,
      "coordinates": { "latitude": 43.67431, "longitude": -79.39668 },
      "transactions": [],
      "price": "$$$$",
      "location": {
        "address1": "134 Avenue Road",
        "address2": null,
        "address3": "",
        "city": "Toronto",
        "zip_code": "M5R 2H6",
        "country": "CA",
        "state": "ON",
        "display_address": ["134 Avenue Road", "Toronto, ON M5R 2H6"]
      },
      "phone": "+14169648686",
      "display_phone": "+1 416-964-8686",
      "distance": 19.22116521243309,
      "business_hours": [{ "day": "Thursday", "start": "1100", "end": "2200" }],
      "attributes": {
        "business_temp_closed": null,
        "menu_url": "http://osteriagiulia.ca/menu/dinner/",
        "open24_hours": null,
        "waitlist_reservation": null
      }
    },
    {
      "id": "K3NW8TEu4QRQvFvHer8v4A",
      "alias": "josos-toronto",
      "name": "Joso's",
      "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/pzNHtL-GLJQvcLl2LVlBqA/o.jpg",
      "is_closed": false,
      "url": "https://www.yelp.com/biz/josos-toronto?adjust_creative=28gGfkLs3igtjVy61lh77Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=28gGfkLs3igtjVy61lh77Q",
      "review_count": 178,
      "categories": [{ "alias": "seafood", "title": "Seafood" }],
      "rating": 4.3,
      "coordinates": { "latitude": 43.6751099, "longitude": -79.39607 },
      "transactions": [],
      "price": "$$$",
      "location": {
        "address1": "202 Davenport Road",
        "address2": "",
        "address3": "",
        "city": "Toronto",
        "zip_code": "M5R 1J2",
        "country": "CA",
        "state": "ON",
        "display_address": ["202 Davenport Road", "Toronto, ON M5R 1J2"]
      },
      "phone": "+14169251903",
      "display_phone": "+1 416-925-1903",
      "distance": 102.3673446381823,
      "business_hours": [{ "day": "Friday", "start": "1100", "end": "2200" }],
      "attributes": {
        "business_temp_closed": null,
        "menu_url": "http://www.josos.com/menu/",
        "open24_hours": null,
        "waitlist_reservation": null
      }
    },
    {
      "id": "B70iTJjcPkuYn8ouUewWgw",
      "alias": "gusto-101-toronto",
      "name": "Gusto 101",
      "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/nVqA7kB5QuXBWX8Nq9-nQQ/o.jpg",
      "is_closed": false,
      "url": "https://www.yelp.com/biz/gusto-101-toronto?adjust_creative=28gGfkLs3igtjVy61lh77Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=28gGfkLs3igtjVy61lh77Q",
      "review_count": 1194,
      "categories": [{ "alias": "italian", "title": "Italian" }],
      "rating": 4,
      "coordinates": { "latitude": 43.645002131066, "longitude": -79.400309337027 },
      "transactions": [],
      "price": "$$",
      "location": {
        "address1": "101 Portland Street",
        "address2": "",
        "address3": "",
        "city": "Toronto",
        "zip_code": "M5V 2N3",
        "country": "CA",
        "state": "ON",
        "display_address": ["101 Portland Street", "Toronto, ON M5V 2N3"]
      },
      "phone": "+14165049669",
      "display_phone": "+1 416-504-9669",
      "distance": 3267.8432435946374,
      "business_hours": [{ "day": "Saturday", "start": "1100", "end": "2200" }],
      "attributes": {
        "business_temp_closed": null,
        "menu_url": null,
        "open24_hours": null,
        "waitlist_reservation": null
      }
    },
    {
      "id": "u71djaZjecGVU1MqMevQ4g",
      "alias": "ristorante-sotto-sotto-toronto",
      "name": "Ristorante Sotto Sotto",
      "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/r5WuvmqtEYjOZZjVtLlhmw/o.jpg",
      "is_closed": false,
      "url": "https://www.yelp.com/biz/ristorante-sotto-sotto-toronto?adjust_creative=28gGfkLs3igtjVy61lh77Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=28gGfkLs3igtjVy61lh77Q",
      "review_count": 136,
      "categories": [{ "alias": "italian", "title": "Italian" }],
      "rating": 3.9,
      "coordinates": { "latitude": 43.67374, "longitude": -79.39646 },
      "transactions": [],
      "price": "$$$",
      "location": {
        "address1": "120 Avenue Road",
        "address2": "",
        "address3": "",
        "city": "Toronto",
        "zip_code": "M5R 2H4",
        "country": "CA",
        "state": "ON",
        "display_address": ["120 Avenue Road", "Toronto, ON M5R 2H4"]
      },
      "phone": "+14169620011",
      "display_phone": "+1 416-962-0011",
      "distance": 67.10055450161477,
      "business_hours": [{ "day": "Sunday", "start": "1100", "end": "2200" }],
      "attributes": {
        "business_temp_closed": null,
        "menu_url": "https://sottosotto.ca/toronto/#anti_anchor",
        "open24_hours": null,
        "waitlist_reservation": null
      }
    },
    {
      "id": "Yl2TN9c23ZGLUBSD9ks5Uw",
      "alias": "byblos-toronto-2",
      "name": "Byblos",
      "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/ciuAYgyPtC7HtljXC4nEnw/o.jpg",
      "is_closed": false,
      "url": "https://www.yelp.com/biz/byblos-toronto-2?adjust_creative=28gGfkLs3igtjVy61lh77Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=28gGfkLs3igtjVy61lh77Q",
      "review_count": 939,
      "categories": [{ "alias": "mediterranean", "title": "Mediterranean" }, { "alias": "middleeastern", "title": "Middle Eastern" }],
      "rating": 4.4,
      "coordinates": { "latitude": 43.647546, "longitude": -79.388123 },
      "transactions": [],
      "price": "$$$$",
      "location": {
        "address1": "11 Duncan Street",
        "address2": "",
        "address3": "",
        "city": "Toronto",
        "zip_code": "M5V 3M2",
        "country": "CA",
        "state": "ON",
        "display_address": ["11 Duncan Street", "Toronto, ON M5V 3M2"]
      },
      "phone": "+16476600909",
      "display_phone": "+1 647-660-0909",
      "distance": 3054.112033364548,
      "business_hours": [{ "day": "Monday", "start": "1100", "end": "2200" }],
      "attributes": {
        "business_temp_closed": null,
        "menu_url": null,
        "open24_hours": null,
        "waitlist_reservation": null
      }
    },
    {
      "id": "snw9iNNLpFYZeHotW00uVA",
      "alias": "lee-toronto-6",
      "name": "Lee",
      "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/Zx0aFKfzKVihu3dn1POGSA/o.jpg",
      "is_closed": false,
      "url": "https://www.yelp.com/biz/lee-toronto-6?adjust_creative=28gGfkLs3igtjVy61lh77Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=28gGfkLs3igtjVy61lh77Q",
      "review_count": 759,
      "categories": [{ "alias": "asianfusion", "title": "Asian Fusion" }],
      "rating": 4.1,
      "coordinates": { "latitude": 43.64719115126137, "longitude": -79.3993497 },
      "transactions": [],
      "price": "$$$",
      "location": {
        "address1": "497 Richmond Street W",
        "address2": "",
        "address3": "",
        "city": "Toronto",
        "zip_code": "M5V 1Y3",
        "country": "CA",
        "state": "ON",
        "display_address": ["497 Richmond Street W", "Toronto, ON M5V 1Y3"]
      },
      "phone": "+14165047867",
      "display_phone": "+1 416-504-7867",
      "distance": 3019.223509317423,
      "business_hours": [{ "day": "Tuesday", "start": "1100", "end": "2200" }],
      "attributes": {
        "business_temp_closed": null,
        "menu_url": "https://www.leerestaurant.com/menu/",
        "open24_hours": null,
        "waitlist_reservation": null
      }
    },
];